### PR TITLE
Genetic_backtester

### PR DESCRIPTION
**Pull request by station384**
incorporates changes in pull #1321
Changed launch files so they execute node directly and not thru bash.
this fixes an orphaned process problem i was seeing where the last
launched process was not getting the kill signal.

Add parameter —run_for to trade command.  this accepts an integer, and
represents how many minutes to trade before doing a clean exit.

### CODE REVIEW

**Review by DeviaVir — APPROVED** [review]

**Comment by narentin** [comment]
If `--run-for` parameter is not given, could we the previous behavior (ie. run forever)?

**Comment by narentin** [comment]
When `--run-for` parameter is used, the following warning appears:
Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.

The following removes the warning:
`var botStartTime = moment().add(so.run_for,'m')`

**Comment by illya13** [comment]
@station384 @DeviaVir 
+1 request to keep previous behavior if no `--run-for` or provide option to have it like `-1`

**Comment by station384** [comment]
@narentin bug fixed by @illya13 in pull #1329

**Pull request merged**
