### PR TITLE
Remove forex_analytics

### PR DESCRIPTION
**Pull request by yellowgh0st**
This is complete removal of forex_analytics which could be one solution to #1765.

### CODE REVIEW

**Comment by yellowgh0st** [comment]
✅ Builds on Ubuntu aswell.
Travis probably lacks of python-dev.

**Comment by yellowgh0st** [comment]
@DeviaVir Also please review this.

**Review by DeviaVir — APPROVED** [review]

**Comment by DeviaVir** [comment]
Not sure what's up with node 8, doesn't seem related.

**Comment by nonkreon** [comment]
@DeviaVir when update.sh is run, the default is to pull the master branch. I think this PR deserves to be in the master branch, can you please merge there too?

**Pull request merged**
