### PR TITLE
trading with kraken

### PR DESCRIPTION
**Pull request by ChairmenMeow100**
I have encountered some problems while trading with kraken, so i updated and rearranged the  extensions/exchanges/kraken/products.json and altered the 42. line in extensions/exchanges/kraken/exchange.js to support all available coins

### CODE REVIEW

**Comment by DeviaVir** [comment]
Did you mean to place these files into https://github.com/DeviaVir/zenbot/tree/unstable/extensions/exchanges/kraken? They're currently in the root.

**Comment by ChairmenMeow100** [comment]
exactly - in the meantime has kraken updated their pairs to support GBP and AUD so i have to re-update both files again ... you will get them soon.

**Comment by ChairmenMeow100** [comment]
this should do the trick ... i am still unable to get CHF and DAI to work (maybe there is still a naming problem) but all of the other pairs work with backfill so i assume it works in general.

**Comment by LuisAlejandro** [comment]
@ChairmenMeow100 The file is in the wrong place, you have to fix the pull request before it can be merged. The file goes in `extensions/exchanges/kraken/exchange.js`

**Comment by ChairmenMeow100** [comment]
@LuisAlejandro sorry, i am completely new to all of this - now i see the problem ... is there a way to fix this pull request? I only found solutions that create a new pull request

**Pull request closed without merging**
