### PR TITLE
Helm chart/v1

### PR DESCRIPTION
**Pull request by Scizoo88**
Added a very basic implementation of a helm chart. There are not many configuration options at the moment for this chart. But it's a good starting point if you want to run ZenBot in a Kubernetes environment.

### CODE REVIEW

**Comment by xunholy** [comment]
@Scizoo88 thanks for putting in the effort to construct this helm chart, I took some time to give it a try and found a few issues with connecting to the MongoDB instance with auth and then an error due to a type error, may I ask if this was ever tested/working for you previously?

**Comment by Scizoo88** [comment]
@xUnholy Hi, sure I run this helm chart on my RKE cluster at home. Did you put in the correct values in the values.yaml file?

**Comment by xunholy** [comment]
What is your current installation method using your configuration?

I attempted to manually hydrate the manifests and apply them and i used the config.js that came with the latest version of zenbot.

**Comment by Scizoo88** [comment]
@xUnholy I can post an detailed how-to on weekend. I see that in the values.yaml file, there is a  wrong Docker image configured, this was an alternative test from another repository and it seems that I didn't remove it, sorry. Can you test it with the official Image "deviavir/zenbot:latest"? I guess this is the problem why the config.js does not work.

**Comment by djjudas21** [comment]
I was considering writing a Helm chart for Zenbot, so I'm pleased to see this. If I get some time this weekend I'll have a look at this and see if we can get it merge-able :+1:

**Pull request closed without merging**
