### PR TITLE
WIP: Rework docs

### PR DESCRIPTION
**Pull request by DJCrashdummy**
1. Hopefully I assumed right and you don't use the wiki (although it is active), but a docs-folder with md-files?

1. This PR is **by far NOT done** yet! - I just wanted to get in touch (and eventually feedback), to see if my ideas/changes are welcome, before I put too much time and effort in it.

1. I want to rework the docs, which means...
    - In first place shorten the main readme, because it almost overwhelms the reader at the first impression (and also as user of zenbot it isn't really a pleasure to handle it).
    - Create single and shorter files grouped by topic in the docs-folder (as it is already done for the `exchanges`).
    - Create a kind of an index-readme at the docs-folder.
    - And of course update some outdated parts.

### CODE REVIEW

**Comment by DeviaVir** [comment]
Hey @DJCrashdummy, thanks for looking at the docs, they are in much need of some TLC.

1. You're right, I disabled the wiki.
2. :+1:
3. :+1:

**Comment by DJCrashdummy** [comment]
Just to mention it:
I'll also change links within this project (whether to other docs, pictures or normal files) to relative links, as the chance is higher that they'll still work if something changes.

**Comment by DJCrashdummy** [comment]
@DeviaVir 
May I change the Node.js version in the install guides to 10.x (maintained until April 2021) in favour of 8.x (maintained until December 2019)? Or are there any downsides/restrictions/problems/etc. I'm not aware of?

**Comment by DeviaVir** [comment]
@DJCrashdummy we're not "officially" testing for 10.x right now, but I don't see a reason why not.
https://github.com/DeviaVir/zenbot/blob/unstable/.travis.yml#L4

**Comment by DJCrashdummy** [comment]
Well... it is IMHO bad practice to recommend not tested things at guides (for beginners). So I rather stick with Node.js 8.x in the docs for now.

---

fyi: I'm running Zenbot (no live-trading for now) with Node.js 10.x and haven't noticed any major drawbacks, just some "`DeprecationWarning`" (3 at `backfill`, 2 at `sim` and 5 at `trade --paper`), but I've also hardly run Zenbot with Node.js 8.x.
Although there is one really annoying regression/bug (no idea if it is known - I haven't worked myself completely through the issues yet): as soon as I'm running a simulation for ~30 days or more, zenbot stalls at different positions and cancels after a few seconds with no message or output. As a workaround I wrote a bash-script myself to retry until completing simulation successfully, because it works sometimes without changing anything... it just took >100 attempts to end one of my simulations successfully.
--> is this known or should i open an issue for that?

btw: @DeviaVir or do you probably plan to jump directly to Node.js 12.x this spring?

**Comment by DeviaVir** [comment]
@DJCrashdummy
> Well... it is IMHO bad practice to recommend not tested things at guides (for beginners). So I rather stick with Node.js 8.x in the docs for now.
> 
> fyi: I'm running Zenbot (no live-trading for now) with Node.js 10.x and haven't noticed any major drawbacks, just some "`DeprecationWarning`" (3 at `backfill`, 2 at `sim` and 5 at `trade --paper`), but I've also hardly run Zenbot with Node.js 8.x.
> Although there is one really annoying regression/bug (no idea if it is known - I haven't worked myself completely through the issues yet): as soon as I'm running a simulation for ~30 days or more, zenbot stalls at different positions and cancels after a few seconds with no message or output. As a workaround I wrote a bash-script myself to retry until completing simulation successfully, because it works sometimes without changing anything... it just took >100 attempts to end one of my simulations successfully.
> --> is this known or should i open an issue for that?
> 
> btw: @DeviaVir or do you probably plan to jump directly to Node.js 12.x this spring?

fair enough. There are currently no future plans, if it's a cheap win to switch to `12.x` we probably will.

**Comment by BAKFR** [comment]
@DJCrashdummy feel free to recommend Node v10
It works with the last version, and I've updated the Travis config.

**Comment by DJCrashdummy** [comment]
@BAKFR thank you for the info!
so if i read your MR correct, it seems to me that the "official" recommended LTS-version is now Node.js 10.x... than i'll change it.

**Comment by DJCrashdummy** [comment]
> [...] there is one really annoying regression/bug [...]: as soon as I'm running a simulation for ~30 days or more, zenbot stalls at different positions and cancels after a few seconds with no message or output. As a workaround I wrote a bash-script myself to retry until completing simulation successfully, because it works sometimes without changing anything... it just took >100 attempts to end one of my simulations successfully.
> --> **is this known or should i open an issue for that?**

any comments on that?!?
is this or something like that already known, or completely new? - because i'm officially clueless regarding that issue. :frowning_face:

**Comment by DJCrashdummy** [comment]
one tiny question about explaining the [**example-trade**](https://github.com/DeviaVir/zenbot#screenshot-and-example-result):
there are some options mentioned like `--sell_rate=-0.006` and `--max_sell_duration=4` for example... i managed to map nearly all used (and outdated resp. renamed) options also from [the linked raw data](https://gist.github.com/carlos8f/b09a734cf626ffb9bb3bcb1ca35f3db4]) to current options, except the `--sell_rate` and `--max_sell_duration`. :confused:

can someone please explain these two options to me or point me to the currently used equivalents!?

---

**EDIT:** `--sell_rate=<value>` and `--max_sell_duration=<value>` seem to be deprecated (or perhaps hardcoded without the possibility to override them) because varying their value doesn't have any impact on the results of a quick simulation.
anyhow... i would appreciate a confirmation or correction, because i'm uncomfortable explaining something i doesn't have fully understood myself.

**Review by DeviaVir — APPROVED** [review]

**Comment by DeviaVir** [comment]
I've gone ahead and merged this in, further work on docs can be done by others building on top of your great work, thank you @DJCrashdummy!

**Pull request merged**
