### PR TITLE
Fix json2csv dependency

### PR DESCRIPTION
**Pull request by maufranchini**
json2csv has been updated to version 4, which has to be constructed slightly different. It's tested and it work.

### CODE REVIEW

**Review by DeviaVir — APPROVED** [review]
:+1: thanks for contributing this fix

**Comment by sweepglass** [comment]
TypeError: Json2csvParser is not a constructor
    at parallel (/home/user/zenbot/scripts/genetic_backtester/darwin.js:345:26)
    at end (/home/user/zenbot/scripts/genetic_backtester/node_modules/run-parallel-limit/index.js:17:15)
    at done (/home/user/zenbot/scripts/genetic_backtester/node_modules/run-parallel-limit/index.js:21:10)
    at each (/home/user/zenbot/scripts/genetic_backtester/node_modules/run-parallel-limit/index.js:28:7)
    at /home/user/zenbot/scripts/genetic_backtester/node_modules/run-parallel-limit/index.js:38:45
    at ChildProcess.proc.on (/home/user/zenbot/lib/backtester.js:572:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

json2csv@4.2.1

**Comment by sweepglass** [comment]
Fixed it. Solution was to remove /home/user/zenbot/scripts/genetic_backtester/node_modules folder. apparently theres older version of json2csv in that folder.

**Comment by hyuce** [comment]
I set it all up from the start. But I still have this problem. can't use bactest anymore. Do you have a suggestion?
```terminal 
TypeError: Json2csvParser is not a constructor
    at parallel (/home/hyuce/CrypT/zenbot/scripts/genetic_backtester/darwin.js:345:26)
    at end (/home/hyuce/CrypT/zenbot/scripts/genetic_backtester/node_modules/run-parallel-limit/index.js:17:15)
    at done (/home/hyuce/CrypT/zenbot/scripts/genetic_backtester/node_modules/run-parallel-limit/index.js:21:10)
    at each (/home/hyuce/CrypT/zenbot/scripts/genetic_backtester/node_modules/run-parallel-limit/index.js:28:7)
    at /home/hyuce/CrypT/zenbot/scripts/genetic_backtester/node_modules/run-parallel-limit/index.js:38:45
    at ChildProcess.proc.on (/home/hyuce/CrypT/zenbot/lib/backtester.js:572:7)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
Resume this backtest later with:
```
> Fixed it. Solution was to remove /home/user/zenbot/scripts/genetic_backtester/node_modules folder. apparently theres older version of json2csv in that folder.

**Comment by hyuce** [comment]
I noticed that "json2csv" in the package.json file: "^ 3.7.3" appears. I think it should be 4.X.

**Pull request merged**
